<?php

function fortune_menu() {
    return array(
        'fortune/%/%' => array(
            'page callback' => 'fortune_page',
            'page arguments' => array(0, 1, 2),
            'access callback' => TRUE,
        ),
    );
}

function fortune_page($command, $fortunes, $riddles) {
    return nl2br(shell_exec("/usr/games/" . $command . " " . $fortunes . "% fortunes " . $riddles . "% riddles"));
}
