<?php

function vouchers_menu() {
    $items = array();

    $items['my-vouchers'] = array(
        'page callback' => 'vouchers_page',
        'page arguments' => array(user_uid_optional_load()),
        'access callback' => true,
    );
    $items['vouchers-admin'] = array(
        'page callback' => 'vouchers_page',
        'access callback' => true,
    );

    return $items;
}

function vouchers_page(stdClass $user = null) {
    return
        theme('buy')
        . theme(
            'table',
            array(
                'header' => array(t('credits'), t('code')),
                'rows' => vouchers_get_all($user),
            )
        );
}

function vouchers_get_all(stdClass $user = null) {
    $csv_file_path = _vouchers_file_path();
    $fh = fopen($csv_file_path, 'r');

    // Throw away the first row as it's the header.
    fgetcsv($fh);

    $vouchers = array();
    while ($csv_line = fgetcsv($fh)) {
        if ($user !== null && $user->uid !== $csv_line[2]) {
            continue;
        }

        $voucher = array(
            'credits' => $csv_line[0],
            'code'    => $csv_line[1],
        );

        if ($user === null) {
            $voucher['uid'] = $csv_line[2];
        }

        $vouchers[] = $voucher;
    }
    return $vouchers;
}

function vouchers_add($credits) {
    $user = user_uid_optional_load();
    $voucher_code = 'AA' . $user->uid . rand(1000000, 9999999);
    file_put_contents(_vouchers_file_path(), "$credits,$voucher_code,{$user->uid}", FILE_APPEND);
    return $voucher_code;
}

function _vouchers_file_path() {
    return drupal_realpath(file_default_scheme() . '://vouchers.csv');
}
