<?php

function id7_custom_theme($existing, $type, $theme, $path) {
  return array(
      'cc-missing' => array(
          'template' => 'cc-missing',
          'variables' => array(),
      ),
      'cc-overview' => array(
          'template' => 'cc-overview',
          'variables' => array(
              'number' => 0,
              'exp_date_month' => 0,
              'exp_date_year' => 0,
              'cvv' => 0,
          )
      ),
      'buy' => array(
          'template' => 'buy',
          'variables' => array(),
      )
  );
}

function id7_custom_menu() {
    $items = array();

    $items['place-order'] = array(
        'page callback' => 'id7_custom_place_order_page',
        'access callback' => true,
    );
    $items['my-vouchers'] = array(
        'page callback' => 'id7_vouchers',
        'access callback' => true,
    );
    $items['my-credit-card'] = array(
        'page callback' => 'id7_cc',
        'access callback' => true,
    );
        $items['my-credit-card/set']  = array(
            'page callback' => 'drupal_get_form',
            'page arguments' => array('form_ccedit'),
            'access callback' => true,
        );
        $items['my-credit-cards/remove/%'] = array(
            'page callback' => 'id7_cc_delete',
            'access callback' => true,
        );

//    $items['all-vouchers'] = array(
//        'page callback' => 'id7_vouchers_all',
//        'access callback' => true,
//    );
//
//    $items['disable-user'] = array(
//        'page callback' => 'id7_disable_user',
//        'access callback' => true,
//    );

    return $items;
}


function form_ccedit($form, &$form_state) {
    $form['#method'] = 'get';
    $form['credit_card_number'] = array(
        '#type' => 'textfield',
        '#maxlength'=> 19,
        '#size' => 19,
        '#title' => 'Credit Card Number',
    );

    $form['expiration_date'] = array(
        '#type' => 'date',
        '#title' => 'Expiration Date',
    );

    $form['credit_card_cvv'] = array(
        '#type' => 'textfield',
        '#title' => 'CVV Code',
        '#size' => 4,
        '#maxlength' => 4,
        '#description' => 'Your 3 or 4 digit security code on the back of your card.',
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Submit'),
    );

    return $form;
}

function form_ccedit_submit($form, &$form_state)
{
    var_dump("yay!<pre>",func_get_args());exit;
}


function id7_vouchers() {
    return <<<HTML
<table>
    <thead>
        <tr>
            <th>Voucher Nr</th>
            <td>Credits</td>
        </tr>
    </thead>
    <tbody>
        <tr><td>12345467890</td><td>5</td></tr>
    </tbody>
</table>
HTML;
}

function id7_vouchers_all() {
    return 'all';
}

function id7_disable_user() {
    return 'user';
}

function id7_custom_buy() {

}

function id7_cc() {

    $card_row = id7_get_card_row_for_user();

    if (empty($card_row)) {
        drupal_goto('my-credit-card/set');
        return '';
    }

    return theme('cc-overview', $card_row);
}

function id7_cc_masking($number) {
    return substr($number, 0, 4) . str_repeat("X", strlen($number) - 8) . substr($number, -4);
}

function id7_get_card_row_for_user() {
    global $user;
    return db_query('SELECT * FROM credit_cards WHERE uid=' . $user->uid)->fetchAssoc();
}

//function id7_custom_form_alter(&$form, &$form_state, $form_id) {
//    echo "<pre>";debug_print_backtrace();var_dump($form_state); echo '</pre>';
//    $function = "id7_custom_{$form_id}_submit";
//    $form['#submit'][] = $function;
//
//    if (function_exists($function)) {
//
//    }
//}

function id7_custom_user_register_form_submit($form, &$form_state) {
    $form_state['redirect'] = 'node/add/business';
}
