<?php

function id7_custom_theme($existing, $type, $theme, $path) {
  return array(
      'cc-missing' => array(
          'template' => 'cc-missing',
          'variables' => array(),
      ),
      'cc-overview' => array(
          'template' => 'cc-overview',
          'variables' => array('rowsHtml' => array())
      ),
  );
}

function id7_custom_menu() {
    $items = array();

    $items['place-order'] = array(
        'page callback' => 'id7_custom_place_order_page',
        'access callback' => true,
    );
    $items['my-vouchers'] = array(
        'page callback' => 'id7_vouchers',
        'access callback' => true,
    );
    $items['my-credit-cards'] = array(
        'page callback' => 'id7_cc',
        'access callback' => true,
    );
        $items['my-credit-cards/add']  = array(
            'page callback' => 'drupal_get_form',
            'page arguments' => array('form_ccedit'),
            'access callback' => true,
        );
        $items['my-credit-cards/%/edit'] = array(
            'page callback' => 'id7_cc_edit',
            'access callback' => true,
        );
        $items['my-credit-cards/%/delete'] = array(
            'page callback' => 'id7_cc_delete',
            'access callback' => true,
        );

//    $items['all-vouchers'] = array(
//        'page callback' => 'id7_vouchers_all',
//        'access callback' => true,
//    );
//
//    $items['disable-user'] = array(
//        'page callback' => 'id7_disable_user',
//        'access callback' => true,
//    );

    return $items;
}


function form_ccedit($form, &$form_state) {
//    $form['#method'] = 'get';
    $form['credit_card_number'] = array(
        '#type' => 'creditfield_cardnumber',
        '#title' => 'Credit Card Number',
        '#maxlength' => 16,
    );

    $form['expiration_date'] = array(
        '#type' => 'creditfield_date',
        '#title' => 'Expiration Date',
    );

    $form['credit_card_cvv'] = array(
        '#type' => 'creditfield_cvv',
        '#title' => 'CVV Code',
        '#maxlength' => 4,
        '#description' => 'Your 3 or 4 digit security code on the back of your card.',
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Submit'),
    );

    return $form;
}

function form_ccedit_submit($form, &$form_state)
{
    var_dump("yay!",func_get_args());exit;
}


function id7_vouchers() {
    return 'OWHAI!';
}

function id7_vouchers_all() {
    return 'all';
}

function id7_disable_user() {
    return 'user';
}

function id7_custom_buy() {

}

function id7_cc() {

    $cards = id7_get_card_rows();

    $rows = array();
    while ($card = $cards->fetchAssoc()) {
        $rows[] = "<tr>" .
            "<td>{$card['number']}</td>".
            "<td>{$card['exp_date_month']}/{$card['exp_date_year']}</td>".
        "</tr>";
    }
    $rows = implode(PHP_EOL, $rows);

    if (empty($rows)) {
        return theme('cc-missing');
    }

    return theme('cc-overview', array('rowsHtml' => $rows));
}

function id7_get_card_rows() {
    global $user;
    return db_query('SELECT * FROM credit_cards WHERE uid=' . $user->uid);
}

//function id7_custom_form_alter(&$form, &$form_state, $form_id) {
//    echo "<pre>";debug_print_backtrace();var_dump($form_state); echo '</pre>';
//    $function = "id7_custom_{$form_id}_submit";
//    $form['#submit'][] = $function;
//
//    if (function_exists($function)) {
//
//    }
//}

function id7_custom_user_register_form_submit($form, &$form_state) {
    $form_state['redirect'] = 'node/add/business';
}
